const weapons = {
  gustave: [
    "Abysseram", "Blodam", "Chevalam", "Cadavreso", "Confuso", "Contorso", "Cruleram", "Cultam",
    "Danseso", "Delaram", "Démonam", "Dualiso", "Gaulteram", "Gesam", "Glaceso", "Lanceram",
    "Liteso", "Noahram", "Nosaram", "Sakaram", "Simoso", "Seeram", "Sireso", "Songeso", "Tireso", "Virleso"
  ],
  verso: [
    "Abysseram", "Blodam", "Chevalam", "Cadavreso", "Confuso", "Contorso", "Cruleram", "Cultam",
    "Danseso", "Delaram", "Démonam", "Dualiso", "Gaulteram", "Gesam", "Glaceso", "Lanceram",
    "Liteso", "Noahram", "Nosaram", "Sakaram", "Simoso", "Seeram", "Sireso", "Songeso", "Tireso", "Virleso"
  ],
  lune: [
    "Arbusculim", "Benisim", "Betelim", "Braselim", "Chapelim", "Charorim", "Choralim", "Colérim",
    "Colim", "Coraillim", "Démineurim", "Elerim", "Kralim", "Lumerim", "Lithelim", "Lunerim",
    "Neigim", "Potierim", "Redalim", "Souffrerim", "Trebuchim", "Troubadim"
  ],
  maelle: [
    "Amphorum", "Brise-barrière", "Battaillum", "Bruleurum", "Chalium", "Chantenum", "Clierum", "Coquillum",
    "Duenum", "Froiddum", "Glaisum", "Lithum", "Maellum", "Medalum", "Melarum", "Plénum",
    "Sekarum", "Stalum", "Tissenum", "Veremum", "Visagesum", "Volestrum", "Yeverum"
  ],
  monoco: [
    "Ballaro", "Boucharo", "Brumaro", "Chromaro", "Fragaro", "Joiro", "Grandaro",
    "Monocaro", "Nusaro", "Sidaro", "Urnaro"
  ],
  sciel: [
    "Algueron", "Blizzon", "Bourgelon", "Charnon", "Chation", "Corderon", "Direton", "Forestion",
    "Garganon", "Gobluson", "Guleson", "Hevason", "Litheson", "Lustrison", "Martenon", "Minason",
    "Moisson", "Ramasson", "Scielson", "Tisseron", "Triston"
  ]
};

const skills = {
  gustave: [
    "Assaut de Lumière",
    "Surcharge",
    "Tir Marquant",
    "Récupération",
    "Surpuissance",
    "Par le feu",
    "Fracas",
    "Frappe Tempête"
  ],
    verso: [
    "Adrénaline",
    "Assaut Ascendant",
    "Assaut Zéro",
    "Attaque éclair",
    "Attaque rapide",
    "Commandement",
    "Déluge d'acier",
    "Enchaînement",
    "Entaille radiante",
    "Étoiles spectrales",
    "Éviscération",
    "Fardeau",
    "Fracture parfaite",
    "Frappe de défi",
    "Frappe tempête",
    "Par le feu",
    "Paradigme",
    "Porte lumière",
    "Purification",
    "Récupération",
    "Surpuissance",
    "Tir marquant",
    "Tranchée berserk",
    "Vitesse Lumière"
  ],
    lune: [
    "Transfert Thermique",
    "Typhon",
    "Vague Accablante",
    "Lueur de soin",
    "Pluie d'éclairs",
    "Rage brûlante",
    "Renaissance",
    "Revitalisation",
    "Secousse sismique",
    "Appel de la tempête",
    "Chaos",
    "Choc Terrestre",
    "Cycle Élémentaire",
    "Danse Foudroyante",
    "Électrisation",
    "Enfer",
    "Fureur Sismique",
    "Genèse",
    "Immolation",
    "Impact Cristallin",
    "Lance de glace"
  ],
    maelle: [
    "Ballet de lames",
    "Botte d'épéiste",
    "Combustion",
    "Contre",
    "Déluge de feu",
    "Dernière chance",
    "Égide",
    "En garde",
    "Flammèche",
    "Fleuret furieux",
    "Foulée vive",
    "Frappe propulsée",
    "Frappe spectrale",
    "Garde affaiblie",
    "Hommage à Gustave",
    "Inflammable",
    "Mezzo Forte",
    "Percée",
    "Pivot offensif",
    "Pyrolyse",
    "Saccage",
    "Stendhal",
    "Toile brûlante",
    "Vengeance"
  ],
    monoco: [
    "Tonnerre de Démineur",
    "Uppercuts de Stalact",
    "Valse de Danseuse",
    "Vendange de Moissonneuse",
    "Séismes de Glaise",
    "Souffle de Contorsionniste",
    "Souffle de Mitrien",
    "Tempête de Dualiste",
    "Tranchant d'Échassier",
    "Trompette de Troubadour",
    "Feu de Sakapatate",
    "Fortification de Boucheclier",
    "Fracassement de Portier",
    "Fureur de Gault",
    "Glace de Chevalière",
    "Guérison de Pèlerin",
    "Lampe d'Amphorion",
    "Lance d'Évêque",
    "Lumière d'Aberration",
    "Lumière du Maître des Lampes",
    "Marteau de Braseleur",
    "Martèlement de Rocher",
    "Mortier de Bénisseur",
    "Néant de Création",
    "Percussion de Sakapatate",
    "Perforation de Chevalière",
    "Ramasseur Bonk",
    "Sang de Cultiste",
    "Absorption d'Arbuscule",
    "Affaiblissement de Clair",
    "Ancre de Bruleur",
    "Barrière de Criuleur",
    "Broyage d'Hexga",
    "Charme de Ballerine",
    "Combo de Chalier",
    "Découpe de Lustrion",
    "Écrasement de Grosse Tête",
    "Empalement de Lancelier",
    "Encouragement d'Orphelin",
    "Énergie de Potier",
    "Entailles de Chapeiler",
    "Entailles de Cultiste",
    "Épée d'Obscur",
    "Estoc de Sakapatate",
    "Explosion de Sakapatate",
    "Fentes de Chevalière"
  ],
    sciel: [
    "Balayage spectral",
    "Carte marquante",
    "Danse du crépuscule",
    "Entaille du crépuscule",
    "Entaille retardante",
    "Fortune enragée",
    "Intervention",
    "Lame spectrale",
    "Lien ardent",
    "Mauvais présage",
    "Notre sacrifice",
    "Ombres volantes",
    "Préparation finale",
    "Présage ciblé",
    "Rapidité",
    "Récolte abondante",
    "Récolte",
    "Sombre purification",
    "Sombre récolte",
    "Sort scellé",
    "Terminus",
    "Tissage de cartes",
    "Vagues obscure"
  ],
};

// ...existing code...

const pictos = [
  "Affinité Inversée",
  "Affinité brûlante",
  "Affaiblissement amélioré",
  "Anti Brulure",
  "Anti Corruption",
  "Anti-Charme",
  "Anti-Gel",
  "Altéré",
  "Anti-Étourdissement",
  "Assurance",
  "Attaque Améliorée",
  "Attaque Affaiblissante",
  "Attaque Accrue",
  "Attaque Combo I",
  "Attaque Combo II",
  "Attaque Combo III",
  "Attaque Protectrice",
  "Attaque Fracturante",
  "Attaque Fragilisante",
  "Attaque Renforçante",
  "Au cœur de l'action",
  "Au seuil de la mort",
  "Bombe Funèbre",
  "Bouclier basique",
  "Bouclier Surpuissant",
  "Bouclier Affinés",
  "Bouclier Fracturante",
  "Brûlures Critiques",
  "Brûlure Prolongée",
  "Brûlure energisante",
  "Buff Curatif",
  "Canon de verre",
  "Carapace Améliorée",
  "Carapace Immédiate",
  "Carapace Prolongée",
  "Carapace Surpuissante",
  "Charges sur altération",
  "Charges sur attaque",
  "Charges sur Brûlure",
  "Charges sur critique",
  "Charges sur contre",
  "Charges sur fracture",
  "Charges sur Marque",
  "Charges sur Étourdissement",
  "Contamination bénéfique",
  "Contre Amélioré I",
  "Contre Amélioré II",
  "Contre amélioré III",
  "Contre Curatif",
  "Contre Fracturant",
  "Critique sur Faiblesses",
  "Critiques sur Vulnérabilité",
  "Danger Protecteur",
  "Danger Surpuissant",
  "Danger Accélérant",
  "Défense aléatoire",
  "Dernier Rempart Accélérant",
  "Dernier Rempart Critique",
  "Dernier Rempart Renforçant",
  "Dernier Rempart Protecteur",
  "Double Marque",
  "Double Brûlure",
  "Échauffement",
  "Élimination Revigorante",
  "Énergie – Attaque I",
  "Énergie – Attaque II",
  "Énergie – Caparace",
  "Énergie – Départ I",
  "Énergie – Départ II",
  "Énergie – Départ III",
  "Énergie – Départ IV",
  "Énergie – Surpuissance",
  "Énergie – Rapidité",
  "Énergie – Faiblesse",
  "Énergie de saut",
  "Énergie – Tour",
  "Energie Douloureuse",
  "Énergie Maitrisée",
  "Énergie Mortelle I",
  "Énergie Mortelle II",
  "Énergie – Parade",
  "Etourdissement critique",
  "Etourdissement opportun",
  "Etourdissement énergisant",
  "Etourdissement curatif",
  "Esquive Renforçante",
  "Feu curatif",
  "Fracture Accélérante",
  "Fracture Brûlante",
  "Fracture Gradient",
  "Fracture marquante",
  "Fracture ralentissante",
  "Fracture Améliorée",
  "Fracture Critique",
  "Fracture Energissante",
  "Fracture Renforcante",
  "Fracture sur attaque",
  "Gradient Énergisant",
  "Guérison Energissante",
  "Guérison Accélérante",
  "Gradient Combattant",
  "Hardiesse",
  "Initiative Améliorée",
  "Initiative",
  "Instant Critique",
  "Insaisissable",
  "Immaculé",
  "Lenteur Fracturante",
  "Lenteur améliorée",
  "Loup Solitaire",
  "Marque Affaiblissante",
  "Marque brûlante",
  "Marque Curative",
  "Marque gratifiante",
  "Marque après Marque",
  "Mode Défensif",
  "Mort préservante",
  "Mort protectrice",
  "Mort Brûlante",
  "Mort Curative",
  "Mort Energissante",
  "Mort Fracturante",
  "Mort Subite",
  "Parade Curative",
  "Parade Périlleuse",
  "Parade renforçante",
  "Partage Curatif",
  "Pleine Puissance",
  "Première Offensive",
  "Peintre",
  "Plus qu'un",
  "Puissance Surpeinte",
  "Purification Drainante",
  "Purification énergisante",
  "Pro du Repli",
  "Plus vif que fort",
  "Polyvalence",
  "Pouvoir Épuisant",
  "Raccourci",
  "Rapidité Améliorée",
  "Rapidité Immédiate",
  "Rapidité Prolongée",
  "Rapidité protectrice",
  "Régénération immédiate",
  "Récupération",
  "Renaissance Énergisante",
  "Renaissance Paradoxale",
  "Renaissance Protégée",
  "Renaissance Surpuissante",
  "Roulette",
  "Seconde Chance",
  "Soin Partagé",
  "Soins Énergisants",
  "Soins Protecteurs",
  "Soins efficaces",
  "Soins Surpuissants",
  "Soutien Efficace",
  "Solidification",
  "Surpuissance Immédiate",
  "Surpuissance Prolongée",
  "Surpuissance améliorée",
  "Surpuissance Rapide",
  "Survivant",
  "Teinte accélérante",
  "Teinte Chargeante",
  "Teinte Curative énergisante",
  "Teinte Préservante",
  "Teinte Purificatrice",
  "Teinte protectrice",
  "Teinte Renforçante",
  "Teinte Temporelle",
  "Teinte de Vie Énergisante",
  "Tirs accélérants",
  "Tir énergisant",
  "Tir Fracturant",
  "Tir Marquant",
  "Tir Perforant",
  "Tir Surpuissant",
  "Tirs Brûlants",
  "Tireur d'élite",
  "Tricheur",
  "Travail d'Équipe",
  "Visée Améliorée",
  "Vitalité de Cléa",
  "Vol de Vie",
  "Vulnérabilité Améliorée"
];
const lumina = [
  { nom: "Affinité Inversée", cout: 5 },
  { nom: "Affinité brûlante", cout: 10 },
  { nom: "Affaiblissement amélioré", cout: 15 },
  { nom: "Anti Brulure", cout: 15 },
  { nom: "Anti Corruption", cout: 10 },
  { nom: "Anti-Charme", cout: 10 },
  { nom: "Anti-Gel", cout: 15 },
  { nom: "Altéré", cout: 3 },
  { nom: "Anti-Étourdissement", cout: 5 },
  { nom: "Assurance", cout: 20 },
  { nom: "Attaque Améliorée", cout: 7 },
  { nom: "Attaque Affaiblissante", cout: 10 },
  { nom: "Attaque Accrue", cout: 10 },
  { nom: "Attaque Combo I", cout: 10 },
  { nom: "Attaque Combo II", cout: 20 },
  { nom: "Attaque Combo III", cout: 30 },
  { nom: "Attaque Protectrice", cout: 10 },
  { nom: "Attaque Fracturante", cout: 1 },
  { nom: "Attaque Fragilisante", cout: 10 },
  { nom: "Attaque Renforçante", cout: 10 },
  { nom: "Au cœur de l'action", cout: 10 },
  { nom: "Au seuil de la mort", cout: 5 },
  { nom: "Bombe Funèbre", cout: 5 },
  { nom: "Bouclier basique", cout: 20 },
  { nom: "Bouclier Surpuissant", cout: 5 },
  { nom: "Bouclier Affinés", cout: 15 },
  { nom: "Brulures Fracturante", cout: 5 }, // coût non précisé, à ajuster
  { nom: "Brûlures Critiques", cout: 5 },
  { nom: "Brûlure Prolongée", cout: 15 },
  { nom: "Brûlure energisante", cout: 10 },
  { nom: "Buff Curatif", cout: 10 },
  { nom: "Canon de verre", cout: 10 },
  { nom: "Carapace Améliorée", cout: 10 },
  { nom: "Carapace Immédiate", cout: 10 },
  { nom: "Carapace Prolongée", cout: 10 }, // coût non précisé, à ajuster
  { nom: "Carapace Surpuissante", cout: 10 },
  { nom: "Charges sur altération", cout: 10 },
  { nom: "Charges sur attaque", cout: 7 },
  { nom: "Charges sur Brûlure", cout: 10 },
  { nom: "Charges sur critique", cout: 10 },
  { nom: "Charges sur contre", cout: 10 },
  { nom: "Charges sur fracture", cout: 5 },
  { nom: "Charges sur Marque", cout: 10 },
  { nom: "Charges sur Étourdissement", cout: 5 },
  { nom: "Charges sur Faiblesse", cout: 5 },
  { nom: "Contamination bénéfique", cout: 15 },
  { nom: "Contre Amélioré I", cout: 3 },
  { nom: "Contre Amélioré II", cout: 5 },
  { nom: "Contre amélioré III", cout: 7 },
  { nom: "Contre Curatif", cout: 10 },
  { nom: "Contre Fracturant", cout: 3 },
  { nom: "Critique sur Faiblesses", cout: 5 },
  { nom: "Critiques sur Vulnérabilité", cout: 5 },
  { nom: "Danger Protecteur", cout: 5 },
  { nom: "Danger Surpuissant", cout: 5 },
  { nom: "Danger Accélérant", cout: 5 },
  { nom: "Défense aléatoire", cout: 5 },
  { nom: "Dernier Rempart Accélérant", cout: 3 },
  { nom: "Dernier Rempart Critique", cout: 3 },
  { nom: "Dernier Rempart Renforçant", cout: 3 },
  { nom: "Dernier Rempart Protecteur", cout: 3 },
  { nom: "Double Marque", cout: 20 },
  { nom: "Double Brûlure", cout: 30 },
  { nom: "Échauffement", cout: 15 },
  { nom: "Élimination Revigorante", cout: 5 },
  { nom: "Énergie – Attaque I", cout: 10 },
  { nom: "Énergie – Attaque II", cout: 15 },
  { nom: "Énergie – Caparace", cout: 10 },
  { nom: "Énergie – Départ I", cout: 5 },
  { nom: "Énergie – Départ II", cout: 10 },
  { nom: "Énergie – Départ III", cout: 15 },
  { nom: "Énergie – Départ IV", cout: 20 },
  { nom: "Énergie – Surpuissance", cout: 10 },
  { nom: "Énergie – Rapidité", cout: 10 },
  { nom: "Énergie – Faiblesse", cout: 3 },
  { nom: "Énergie de saut", cout: 5 },
  { nom: "Énergie – Tour", cout: 20 },
  { nom: "Energie Douloureuse", cout: 10 },
  { nom: "Énergie Maitrisée", cout: 40 },
  { nom: "Énergie Mortelle I", cout: 2 },
  { nom: "Énergie Mortelle II", cout: 2 },
  { nom: "Énergie – Parade", cout: 15 },
  { nom: "Etourdissement critique", cout: 5 },
  { nom: "Etourdissement opportun", cout: 10 },
  { nom: "Etourdissement énergisant", cout: 10 },
  { nom: "Etourdissement curatif", cout: 10 },
  { nom: "Esquive Renforçante", cout: 5 },
  { nom: "Feu curatif", cout: 10 },
  { nom: "Fracture Accélérante", cout: 3 },
  { nom: "Fracture Brûlante", cout: 3 },
  { nom: "Fracture Gradient", cout: 5 },
  { nom: "Fracture marquante", cout: 5 },
  { nom: "Fracture ralentissante", cout: 5 },
  { nom: "Fracture Améliorée", cout: 10 },
  { nom: "Fracture Critique", cout: 5 },
  { nom: "Fracture Energissante", cout: 3 },
  { nom: "Fracture Renforcante", cout: 3 },
  { nom: "Fracture sur attaque", cout: 10 },
  { nom: "Gradient Énergisant", cout: 10 },
  { nom: "Guérison Energissante", cout: 10 },
  { nom: "Guérison Accélérante", cout: 5 },
  { nom: "Gradient Combattant", cout: 5 },
  { nom: "Hardiesse", cout: 15 },
  { nom: "Initiative Améliorée", cout: 5 },
  { nom: "Initiative", cout: 10 }, // coût non précisé, à ajuster
  { nom: "Instant Critique", cout: 5 },
  { nom: "Insaisissable", cout: 1 },
  { nom: "Immaculé", cout: 10 },
  { nom: "Lenteur Fracturante", cout: 5 },
  { nom: "Lenteur améliorée", cout: 15 },
  { nom: "Loup Solitaire", cout: 1 },
  { nom: "Marque Affaiblissante", cout: 10 },
  { nom: "Marque brûlante", cout: 15 },
  { nom: "Marque Curative", cout: 20 },
  { nom: "Marque gratifiante", cout: 5 },
  { nom: "Marque après Marque", cout: 10 },
  { nom: "Mode Défensif", cout: 1 },
  { nom: "Mort préservante", cout: 10 },
  { nom: "Mort protectrice", cout: 5 },
  { nom: "Mort Brûlante", cout: 5 },
  { nom: "Mort Curative", cout: 5 },
  { nom: "Mort Energissante", cout: 5 },
  { nom: "Mort Fracturante", cout: 5 },
  { nom: "Mort Subite", cout: 1 }, // coût non précisé, à ajuster
  { nom: "Parade Curative", cout: 5 },
  { nom: "Parade Périlleuse", cout: 5 },
  { nom: "Parade renforçante", cout: 5 },
  { nom: "Partage Curatif", cout: 5 },
  { nom: "Pleine Puissance", cout: 15 },
  { nom: "Première Offensive", cout: 5 },
  { nom: "Peintre", cout: 10 },
  { nom: "Plus qu'un", cout: 1 },
  { nom: "Puissance Surpeinte", cout: 5 },
  { nom: "Purification Drainante", cout: 15 },
  { nom: "Purification énergisante", cout: 10 },
  { nom: "Pro du Repli", cout: 40 },
  { nom: "Plus vif que fort", cout: 10 },
  { nom: "Polyvalence", cout: 5 },
  { nom: "Pouvoir Épuisant", cout: 2 },
  { nom: "Raccourci", cout: 5 },
  { nom: "Rapidité Améliorée", cout: 10 },
  { nom: "Rapidité Immédiate", cout: 10 },
  { nom: "Rapidité Prolongée", cout: 10 },
  { nom: "Rapidité protectrice", cout: 10 },
  { nom: "Régénération immédiate", cout: 10 },
  { nom: "Récupération", cout: 10 },
  { nom: "Renaissance Énergisante", cout: 5 },
  { nom: "Renaissance Paradoxale", cout: 5 },
  { nom: "Renaissance Protégée", cout: 5 },
  { nom: "Renaissance Surpuissante", cout: 3 },
  { nom: "Roulette", cout: 5 },
  { nom: "Seconde Chance", cout: 40 },
  { nom: "Soin Partagé", cout: 10 },
  { nom: "Soins Énergisants", cout: 10 },
  { nom: "Soins Protecteurs", cout: 10 },
  { nom: "Soins efficaces", cout: 30 },
  { nom: "Soins Surpuissants", cout: 10 },
  { nom: "Soutien Efficace", cout: 5 },
  { nom: "Solidification", cout: 10 },
  { nom: "Surpuissance Immédiate", cout: 10 },
  { nom: "Surpuissance Prolongée", cout: 10 },
  { nom: "Surpuissance améliorée", cout: 10 },
  { nom: "Surpuissance Rapide", cout: 10 },
  { nom: "Survivant", cout: 20 },
  { nom: "Teinte accélérante", cout: 5 },
  { nom: "Teinte Chargeante", cout: 2 },
  { nom: "Teinte Curative énergisante", cout: 1 },
  { nom: "Teinte Préservante", cout: 10 },
  { nom: "Teinte Purificatrice", cout: 5 },
  { nom: "Teinte protectrice", cout: 5 },
  { nom: "Teinte Renforçante", cout: 5 },
  { nom: "Teinte Temporelle", cout: 10 },
  { nom: "Teinte de Vie Énergisante", cout: 10 },
  { nom: "Tirs accélérants", cout: 3 },
  { nom: "Tir énergisant", cout: 10 },
  { nom: "Tir Fracturant", cout: 1 },
  { nom: "Tir Marquant", cout: 3 }, // coût non précisé, à ajuster
  { nom: "Tir Perforant", cout: 2 },
  { nom: "Tir Surpuissant", cout: 3 }, // coût non précisé, à ajuster
  { nom: "Tirs Brûlants", cout: 3 },
  { nom: "Tireur d'élite", cout: 15 },
  { nom: "Tricheur", cout: 40 },
  { nom: "Travail d'Équipe", cout: 5 },
  { nom: "Visée Améliorée", cout: 3 },
  { nom: "Vitalité de Cléa", cout: 30 },
  { nom: "Vol de Vie", cout: 15 },
  { nom: "Vulnérabilité Améliorée", cout: 15 }
];
module.exports = { weapons, skills, pictos, lumina };